### ISSUE TITLE
Malformed protocol detected

### ISSUE THREAD

**Issue by goofpunk** [haji-ali/maccalfw#1]
Getting emacs set up again after not using it for a while, and it's my first time using straight, so apologies if there's an easy solution here that I can't see, but when I add the use-package command to my init file, I keep getting this error:

`error: Malformed protocol detected: (:host github :repo "https://github.com/haji-ali/maccalfw.git")`

I'm not sure what the issue is or how to fix it. Thanks for any help, I'm really excited about this package!

**Comment by haji-ali** [comment]
Thanks for point this out. Indeed, the readme had a mistake. The correct straight command should be

```
(use-package maccalfw
  :commands maccalfw-open
  :straight (:host github
                   :repo "haji-ali/maccalfw"
                   :files ("maccalfw.el" ("src" . "src"))))
```

**Comment by goofpunk** [comment]
Awesome, that lets the install work, thank you! Unfortunately I've now been presented with a new set of errors when trying to launch maccalfw:

```
Warning: setting attribute ‘:foreground’ of face ‘cfw:face-holiday’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘cfw:face-today’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:background’ of face ‘cfw:face-today’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘cfw:face-toolbar’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:background’ of face ‘cfw:face-toolbar’: nil value is invalid, use ‘unspecified’ instead.
Warning: Optimization failure for make-cfw:event: Handler: make-cfw:event--cmacro
(error "Keyword argument :status not one of (:title :start-date :start-time :end-date :end-time :description :location :source)")
Warning: Optimization failure for make-cfw:event: Handler: make-cfw:event--cmacro
(error "Keyword argument :status not one of (:title :start-date :start-time :end-date :end-time :description :location :source)")
file-name-directory: Symbol’s function definition is void: feature-file
Package cl is deprecated
```

**Comment by haji-ali** [comment]
Unfortunately many of these warnings are from calfw which hasn’t been updated for a while. 

Can I suggest that you use my calfw fork which fixes most (if not all) of these issues?
